//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftedCenterProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign_Up
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int phoneNumber { get; set; }
        public string Status { get; set; }
        public int subjectID { get; set; }
        public System.DateTime createdDate { get; set; }
        public byte isActive { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
