//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftedCenterProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Student_Class = new HashSet<Student_Class>();
        }
    
        public int ID { get; set; }
        public int lecturerID { get; set; }
        public int subjectID { get; set; }
        public System.DateTime startDay { get; set; }
        public System.DateTime finishDay { get; set; }
        public System.DateTime createDate { get; set; }
        public byte isActive { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Class> Student_Class { get; set; }
    }
}
