//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftedCenterProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Class
    {
        public int ID { get; set; }
        public int studentID { get; set; }
        public int classID { get; set; }
        public System.DateTime createDate { get; set; }
        public byte isActive { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
